export default {
  files: ["**", ".*/**"],
  ignorePaths: [
    ".git",
    ".gitignore",
    ".github",
    ".pre-commit-config.yaml",
    ".secrets.baseline",
    "Makefile",
    "CHANGELOG.md",
    "node_modules",
    "package.json",
    "pnpm-lock.yaml",
    "supabase",
    "docker-compose.yaml",
    "app/components/molecules/AsciiDonut.tsx",
  ],
  words: [
    "workdir",
    "tseslint",
    "jsxa",
    "espree",
    "Gleb",
    "Khaykin",
    "khaykingleb",
    "daisyui",
    "wheatfield",
    "conventionalcommits",
    "vercel",
    "katex",
    "pageid",
    "changefreq",
    "doesn",
    "supabase",
    "jsonencode",
    "signup",
  ],
};
