create table public.posts (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    title character varying not null,
    slug character varying not null,
    notion_page_id character varying not null,
    tags text [] not null,
    image_url character varying not null
);

alter table public.posts enable row level security;

create unique index posts_pkey on public.posts using btree (id);

create unique index posts_slug_key on public.posts using btree (slug);

alter table public.posts add constraint posts_pkey
primary key using index posts_pkey;

alter table public.posts add constraint posts_slug_key
unique using index posts_slug_key;

grant delete, insert, references, select, trigger, truncate, update
on table public.posts to anon;

grant delete, insert, references, select, trigger, truncate, update
on table public.posts to authenticated;

grant delete, insert, references, select, trigger, truncate, update
on table public.posts to service_role;
